# =========================================================
# 1. DATABASE CONFIGURATION
# =========================================================
databases:
  - name: inventorydb
    plan: free
    databaseName: inventory
    user: inventory

# =========================================================
# 2. APPLICATION SERVICES
# =========================================================
services:
  # --- A. DJANGO BACKEND (API) ---
  - type: web
    name: inventory-api
    plan: free
    runtime: python
    # CRUCIAL: Point to the backend folder containing manage.py
    rootDir: backend 
    
    # Use the build.sh script defined previously
    buildCommand: './build.sh' 
    
    # START COMMAND: Points to your Django project's WSGI file
    startCommand: 'gunicorn inventory.wsgi:application' 
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventorydb
          property: connectionString
      
      - key: SECRET_KEY
        generateValue: true
      
      # SETTINGS MODULE: Must match your project name and production settings file
      - key: DJANGO_SETTINGS_MODULE 
        # Assuming you create 'production.py' inside your project's settings directory
        value: inventory.settings.production 
      
      - key: WEB_CONCURRENCY
        value: 4

  # --- B. REACT FRONTEND (STATIC SITE) ---
  - type: static_site
    name: inventory-frontend
    
    # CRUCIAL: Point to the frontend folder
    rootDir: frontend
    
    buildCommand: 'npm install && npm run build'
    publishPath: build 
    
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
