databases:
  - name: inventorydb
    plan: free
    databaseName: inventory
    user: inventory

services:
  - type: web
    plan: free
    name: inventory
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn inventory.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventorydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4