databases:
  - name: inventorydb
    plan: free
    databaseName: inventory
    user: inventory

services:
  - type: web
    plan: free
    name: inventory
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn inventory.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventorydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

 # --- B. REACT FRONTEND (STATIC SITE) ---
  - type: static_site
    name: inventory-frontend
    
    # Crucial: Specify the React root directory
    rootDir: frontend
    
    # Command to install Node dependencies and run the build script
    buildCommand: 'npm install && npm run build'
    
    # The directory where the compiled static files (HTML, JS, CSS) are saved
    publishPath: build 
    
    # Custom Headers (Recommended)
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
