# Generated by Django 5.2.7 on 2025-10-04 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_point', models.IntegerField(default=10, help_text='Minimum stock level before reordering.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Warehouse A', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Stock Levels',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Stock In (Purchase/Return)'), ('OUT', 'Stock Out (Sale/Usage)'), ('ADJ', 'Adjustment (Count/Loss)')], max_length=3)),
                ('quantity_change', models.IntegerField(help_text='Positive for IN/ADJ+, negative for OUT/ADJ-')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
