# Generated by Django 5.2.7 on 2025-10-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_stock_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
